export const TOGGLE_EVENT = "TOGGLE_EVENT";
export const SET_EVENT = "SET_EVENT";
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const LOAD_MORE_PRODUCTS = "LOAD_MORE_PRODUCTS";
    